### ISSUE TITLE
ButtleOFX failing to start

### ISSUE THREAD

**Issue by JamesWrigley** [buttleofx/ButtleOFX#55]
Hi there,
I followed all the compilation instructions to the letter, but when I run 'python buttleApp.py',  I get this error:

```
Traceback (most recent call last):
  File "buttleApp.py", line 11, in <module>
    import buttleofx
  File "/home/james/src/ButtleOFX/buttleofx/__init__.py", line 1, in <module>
    from .main import ButtleApp
  File "/home/james/src/ButtleOFX/buttleofx/main.py", line 16, in <module>
    from pyTuttle import tuttle
ImportError: No module named pyTuttle
```

In fact, running find --name "_pyTuttle_" in the root directory failed to turn up anything. I'm running Fedora 19, 64bit.
Any ideas?

Thanks,
JamesNZ

**Comment by fabiencastan** [comment]
Hi,

We are just moving from PySide/Qt4.8/QtQuick1 to PyQt5/Qt5/QtQuick2. Almost everything is currently broken...
And it's a so recent change that we have not even updated the Readme. This change will simplify the installation, because it remove dependencies to: qmlcanvas and qtquickcontrols from qt-labs. They are now parts of QtQuick 2.

About your error, the probleme is that ButtleOFX is a GUI around the TuttleOFX framework. So you need to have TuttleOFX installed.
I'm sorry that this is not written in the readme... But currently we have not put effort for distribution because the project is under very early development.

You could download TuttleOFX binaries (use the "production" version):
http://www.tuttleofx.org/download

We hope to make a release in februar. So I recommand you to wait for this release, if you would like to test it as a end user.

If you would like to test the compositing features of TuttleOFX, you could test it using the command line:
http://www.tuttleofx.org/user-documentation/command-line-examples

**Comment by JamesWrigley** [comment]
Ah I see.

Thanks,
JamesNZ
